import "./globals.css";
import Navbar from "./components/Navbar";

import { UserProvider } from '@auth0/nextjs-auth0/client';
import { StateProvider } from "./data/Context";
import { Footer } from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <StateProvider>
        <body className={`antialiased`}>
          <Navbar />
          {children}
          <Footer />
        </body>
        </StateProvider>
      </UserProvider>
    </html>
  );
}
